### ISSUE TITLE
Auto run from cron or call from another plugin

### ISSUE THREAD

**Issue by magnet0** [dimavroudis/AutoConvert-Greeklish-Permalink#3]
Καλημέρα Δημήτρη,
Hello,

I would like create a cron job to run the old permalink creation procedure. Is that possible?
Or call the function from another plugin?
I am inserting post through CyberSEO Lite and all new posts are created with greek permalinks. 

Thank you

**Comment by magnet0** [comment]
Just forget it, As I can see it works OK.
Thank you

**Comment by dimavroudis** [comment]
@magnet0 I am glad everything worked ok.
