### ISSUE TITLE
Cannot convert old posts/terms on XTemos themes

### ISSUE THREAD

**Issue by Gebrukal** [dimavroudis/AutoConvert-Greeklish-Permalink#4]
Greetings. It seems that there's an issue on your old posts/terms conversion when a theme by XTemos (Basel / Woodmart) is enabled. 
When trying to convert with these themes enabled, the styling of your plugin changes dramatically (the autofill option is gone and it is replaced by a typical list) as seen below. If I try to select a post/term to convert to greeklish, it redirects me to the General Settings without even starting the conversion. 
Issue peristed even with all of the other plugins disabled and solved when turned to TwentyTwenty theme (without the disabled plugins).

![Screenshot_1](https://user-images.githubusercontent.com/36993463/95739630-cd5bbf80-0c93-11eb-8125-d245664b8125.png)

Just wanted to inform you about this issue, because these are some of the most selling themes and it may also happen with other themes.

**Comment by dimavroudis** [comment]
It seems there was an issue with loading the JavaScript files. In the 4.0.3 the issue has been fixed.
